# Generated by Django 2.2.5 on 2019-11-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('jobName', models.CharField(db_column='jobName', max_length=6, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('exp', models.CharField(blank=True, max_length=10, null=True)),
                ('edu', models.CharField(blank=True, max_length=2, null=True)),
                ('offerNumber', models.CharField(blank=True, db_column='offerNumber', max_length=4, null=True)),
                ('jobInfo', models.CharField(blank=True, db_column='jobInfo', max_length=50, null=True)),
                ('companyType', models.CharField(blank=True, db_column='companyType', max_length=10, null=True)),
                ('staffNumbe', models.CharField(blank=True, db_column='staffNumber', max_length=10, null=True)),
                ('companyOrientation', models.CharField(blank=True, db_column='companyOrientation', max_length=5, null=True)),
            ],
        ),
    ]
