# Generated by Django 2.1.1 on 2019-11-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(db_column='jobName', max_length=6)),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('exp', models.CharField(max_length=10)),
                ('edu', models.CharField(max_length=2)),
                ('offerNumber', models.CharField(db_column='offerNumber', max_length=4)),
                ('jobInfo', models.CharField(db_column='jobInfo', max_length=70)),
                ('companyType', models.CharField(db_column='companyType', max_length=10)),
                ('staffNumber', models.CharField(db_column='staffNumber', max_length=20)),
                ('companyOrientation', models.CharField(db_column='companyOrientation', max_length=5)),
            ],
            options={
                'db_table': 'jobinfo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobinfo',
            unique_together={('jobName', 'company')},
        ),
    ]
