# Generated by Django 2.1.1 on 2020-03-21 09:14

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='真实姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='手机号码')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='工作地址')),
                ('workingYear', models.CharField(blank=True, max_length=32, verbose_name='工作年龄')),
                ('blog', models.URLField(blank=True, verbose_name='博客地址')),
                ('edu', models.CharField(blank=True, max_length=16, verbose_name='教育水平')),
                ('glory', models.TextField(blank=True, verbose_name='获得荣耀')),
                ('exp', models.TextField(blank=True, verbose_name='工作经验')),
                ('description', models.TextField(blank=True, verbose_name='个人经历')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(db_column='jobName', max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('exp', models.CharField(max_length=250)),
                ('edu', models.CharField(max_length=250)),
                ('offerNumber', models.CharField(db_column='offerNumber', max_length=250)),
                ('jobInfo', models.TextField(db_column='jobInfo')),
                ('companyType', models.CharField(db_column='companyType', max_length=250)),
                ('staffNumber', models.CharField(db_column='staffNumber', max_length=250)),
                ('companyOrientation', models.CharField(db_column='companyOrientation', max_length=250)),
                ('jobURL', models.CharField(db_column='jobURL', max_length=255)),
                ('unifyName', models.CharField(blank=True, db_column='unifyName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'jobinfo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobinfo',
            unique_together={('jobName', 'company', 'date')},
        ),
    ]
