# Generated by Django 2.1.1 on 2020-03-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personalSKill',
            field=models.CharField(blank=True, max_length=256, verbose_name='个人技能'),
        ),
        migrations.AddField(
            model_name='user',
            name='professioanlSKill',
            field=models.CharField(blank=True, max_length=256, verbose_name='专业技能'),
        ),
        migrations.AddField(
            model_name='user',
            name='toolSKill',
            field=models.CharField(blank=True, max_length=256, verbose_name='工具使用技能'),
        ),
    ]
