# Generated by Django 2.1.1 on 2020-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_data', '0002_auto_20200407_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blog',
            field=models.URLField(blank=True, null=True, verbose_name='博客地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址'),
        ),
    ]
