# Generated by Django 2.1.1 on 2020-03-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('big_data', '0002_auto_20200331_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personalSKill',
            new_name='personalSkill',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='professioanlSKill',
            new_name='professioanlSkill',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='toolSKill',
            new_name='toolSkill',
        ),
    ]
