# Generated by Django 2.1.1 on 2020-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_data', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@dd.com', max_length=254),
        ),
    ]
