# Generated by Django 2.1.1 on 2020-02-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_data', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
