# Generated by Django 2.1.1 on 2020-01-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(db_column='jobName', max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('exp', models.CharField(max_length=250)),
                ('edu', models.CharField(max_length=250)),
                ('offerNumber', models.CharField(db_column='offerNumber', max_length=250)),
                ('jobInfo', models.TextField(db_column='jobInfo')),
                ('companyType', models.CharField(db_column='companyType', max_length=250)),
                ('staffNumber', models.CharField(db_column='staffNumber', max_length=250)),
                ('companyOrientation', models.CharField(db_column='companyOrientation', max_length=250)),
                ('jobURL', models.CharField(db_column='jobURL', max_length=255)),
                ('unifyName', models.CharField(blank=True, db_column='unifyName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'jobinfo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobinfo',
            unique_together={('jobName', 'company', 'date')},
        ),
    ]
