# Generated by Django 2.1.1 on 2020-02-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
